"""Canonical literal RPC catalog; each route has one explicit invocation contract."""

from .rpc_route_context import RpcRoute, build_routes
from .rpc_route_context import handle_runtime_context
from .rpc_catalog_core import (
    handle_prompts_list,
    handle_prompts_optimize,
    handle_providers_list,
    handle_models_list,
    handle_tools_list,
)
from .rpc_briefing import handle_briefing_get
from .rpc_persona import (
    handle_persona_get,
    handle_persona_settings_get,
    handle_persona_settings_update,
    handle_persona_context_get,
    handle_persona_list,
    handle_persona_create,
    handle_persona_select,
    handle_persona_read_file,
    handle_persona_write_file,
    handle_persona_flavor_draft,
    handle_persona_flavor_save,
)
from .rpc_market_intraday import (
    handle_market_intraday_get,
    handle_market_intraday_intervals,
    handle_market_ticker_profile_get,
)
from .rpc_home import handle_focus_get, handle_focus_update, handle_home_snapshot
from .rpc_memory import (
    handle_memory_list,
    handle_memory_upsert,
    handle_memory_archive,
    handle_memory_approve,
    handle_memory_discard,
)
from .rpc_user_notes import handle_user_notes_list, handle_user_notes_approve, handle_user_notes_discard
from .rpc_runtime import handle_runtime_workspace_browse, handle_runtime_workspace_set
from .rpc_provider_auth import (
    handle_provider_auth_status,
    handle_provider_auth_begin_login,
    handle_provider_auth_complete_login,
    handle_provider_auth_logout,
)
from .rpc_messaging import (
    handle_messaging_config_get,
    handle_messaging_config_update,
    handle_messaging_test,
    handle_messaging_destinations_list,
    handle_messaging_destinations_upsert,
    handle_messaging_destinations_delete,
    handle_messaging_routes_list,
    handle_messaging_routes_upsert,
    handle_messaging_routes_delete,
    handle_messaging_routes_resolve,
)
from .rpc_market import (
    handle_market_chart_series_get,
    handle_market_brief_get,
    handle_market_brief_run,
    handle_market_ledger_get,
    handle_market_dashboard_get,
    handle_market_interpret,
    handle_market_read_get,
    handle_market_refresh,
    handle_market_ticker_evidence_get,
    handle_market_ticker_fundamentals_get,
    handle_market_financial_metrics_list,
    handle_market_financial_series_get,
    handle_market_ticker_get,
    handle_market_universe_get,
    handle_market_backtest_run,
    handle_market_backtest_stress_test,
)
from .rpc_market_formula import handle_market_chart_formulas_get
from .rpc_market_webull import (
    handle_market_webull_account_select,
    handle_market_webull_accounts,
    handle_market_webull_auth,
    handle_market_webull_orders_sync,
    handle_market_webull_pnl_get,
    handle_market_webull_status,
    handle_market_webull_sync,
    handle_market_webull_watchlists_import,
)
from .rpc_market_watchlist import (
    handle_market_watchlist_get,
    handle_market_watchlist_add,
    handle_market_watchlist_remove,
    handle_market_watchlist_list_create,
    handle_market_watchlist_list_delete,
    handle_market_watchlist_list_role,
    handle_market_watchlist_list_select,
    handle_market_symbols_search,
)
from .rpc_market_calendar import handle_market_calendar_get
from .rpc_market_yield_curve import handle_market_yield_curve_get
from .rpc_chat import handle_chat_abort, handle_chat_history, handle_chat_send
from .rpc_fleet import (
    handle_fleet_archive,
    handle_fleet_create,
    handle_fleet_get,
    handle_fleet_list,
    handle_fleet_send,
)
from .rpc_nasa import handle_nasa_apod, handle_nasa_apod_list
from .rpc_permissions import (
    handle_permissions_allowlist_add,
    handle_permissions_allowlist_list,
    handle_permissions_allowlist_remove,
)
from .rpc_observability import (
    handle_observability_run_get,
    handle_observability_settings_get,
    handle_observability_settings_update,
    handle_observability_traces_purge,
)
from .rpc_sessions import (
    handle_approvals_list,
    handle_pulse_create_from_session,
    handle_pulse_dismiss,
    handle_pulse_list,
    handle_pulse_save,
    handle_sessions_archive,
    handle_sessions_artifacts,
    handle_sessions_create,
    handle_sessions_debug_copy,
    handle_sessions_export,
    handle_sessions_list,
    handle_sessions_merge_create,
    handle_sessions_merge_state,
    handle_chat_decide_approval,
    handle_sessions_rename,
    handle_sessions_revert_edit,
    handle_sessions_run,
    handle_sessions_runs,
    handle_sessions_resolve,
    handle_sessions_state,
)
from .rpc_workspace import (
    handle_workspace_list_files,
    handle_workspace_read_file,
    handle_workspace_write_file,
)
from .rpc_market_chart import (
    handle_chart_workspace_get,
    handle_chart_workspace_update,
    handle_chart_capture,
    handle_chart_read,
    handle_chart_document_get,
    handle_chart_apply,
    handle_chart_undo,
    handle_chart_rendered,
)
from .rpc_market_forecasts import (
    request_forecast,
    get_forecast,
    list_forecasts,
    cancel_forecast,
    amend_forecast,
    update_tracking,
    rendered_forecast,
)
from .rpc_market_alerts import (
    handle_market_alerts_list,
    handle_market_alerts_create,
    handle_market_alerts_save,
    handle_market_alerts_cancel,
    handle_market_alerts_state,
    handle_market_alerts_catalogue,
)
from .rpc_market_screeners import (
    handle_market_screeners_get, handle_market_screeners_preview, handle_market_screeners_run,
    handle_market_screeners_run_get, handle_market_screeners_handoff, handle_market_screeners_setup_get,
)
from .rpc_market_scans import (
    handle_market_scans_get,
    handle_market_scans_save,
    handle_market_scans_archive,
    handle_market_scans_preview,
    handle_market_scans_run,
    handle_market_scans_run_get,
)
from .rpc_market_notifications import (
    handle_market_notifications_get,
    handle_market_notifications_test,
    handle_market_notifications_action,
)
from .rpc_market_quote import handle_market_quote

RPC_ROUTES = build_routes(
    [
        ("chat.send", RpcRoute(handle_chat_send, "chat")),
        ("chat.abort", RpcRoute(handle_chat_abort, "standard")),
        ("chat.history", RpcRoute(handle_chat_history, "standard")),
        ("fleet.list", RpcRoute(handle_fleet_list, "standard")),
        ("fleet.get", RpcRoute(handle_fleet_get, "standard")),
        ("fleet.create", RpcRoute(handle_fleet_create, "standard")),
        ("fleet.send", RpcRoute(handle_fleet_send, "fleet")),
        ("fleet.archive", RpcRoute(handle_fleet_archive, "standard")),
        ("sessions.list", RpcRoute(handle_sessions_list, "standard")),
        ("prompts.list", RpcRoute(handle_prompts_list, "catalog")),
        ("prompts.optimize", RpcRoute(handle_prompts_optimize, "standard")),
        ("providers.list", RpcRoute(handle_providers_list, "without_params")),
        ("models.list", RpcRoute(handle_models_list, "standard")),
        ("tools.list", RpcRoute(handle_tools_list, "without_params")),
        ("observability.settings.get", RpcRoute(handle_observability_settings_get, "without_params")),
        ("observability.settings.update", RpcRoute(handle_observability_settings_update, "standard")),
        ("observability.traces.purge", RpcRoute(handle_observability_traces_purge, "without_params")),
        ("observability.run.get", RpcRoute(handle_observability_run_get, "standard")),
        ("persona.get", RpcRoute(handle_persona_get, "standard")),
        ("persona.settings.get", RpcRoute(handle_persona_settings_get, "without_params")),
        ("persona.settings.update", RpcRoute(handle_persona_settings_update, "standard")),
        ("persona.context", RpcRoute(handle_persona_context_get, "standard")),
        ("persona.flavor.draft", RpcRoute(handle_persona_flavor_draft, "standard")),
        ("persona.flavor.save", RpcRoute(handle_persona_flavor_save, "standard")),
        ("persona.list", RpcRoute(handle_persona_list, "standard")),
        ("persona.create", RpcRoute(handle_persona_create, "standard")),
        ("persona.select", RpcRoute(handle_persona_select, "standard")),
        ("persona.readFile", RpcRoute(handle_persona_read_file, "standard")),
        ("persona.writeFile", RpcRoute(handle_persona_write_file, "standard")),
        ("briefing.get", RpcRoute(handle_briefing_get, "without_params")),
        ("market.intraday.get", RpcRoute(handle_market_intraday_get, "standard")),
        ("market.intraday.intervals", RpcRoute(handle_market_intraday_intervals, "standard")),
        ("market.ticker.profile.get", RpcRoute(handle_market_ticker_profile_get, "standard")),
        ("home.snapshot", RpcRoute(handle_home_snapshot, "standard")),
        ("home.focus.get", RpcRoute(handle_focus_get, "standard")),
        ("home.focus.update", RpcRoute(handle_focus_update, "standard")),
        ("memory.list", RpcRoute(handle_memory_list, "standard")),
        ("memory.upsert", RpcRoute(handle_memory_upsert, "standard")),
        ("memory.archive", RpcRoute(handle_memory_archive, "standard")),
        ("memory.approve", RpcRoute(handle_memory_approve, "standard")),
        ("memory.discard", RpcRoute(handle_memory_discard, "standard")),
        ("userNotes.list", RpcRoute(handle_user_notes_list, "standard")),
        ("userNotes.approve", RpcRoute(handle_user_notes_approve, "standard")),
        ("userNotes.discard", RpcRoute(handle_user_notes_discard, "standard")),
        ("runtime.context", RpcRoute(handle_runtime_context, "context")),
        ("runtime.workspace.browse", RpcRoute(handle_runtime_workspace_browse, "without_params")),
        ("runtime.workspace.set", RpcRoute(handle_runtime_workspace_set, "standard")),
        ("providerAuth.status", RpcRoute(handle_provider_auth_status, "standard")),
        ("providerAuth.beginLogin", RpcRoute(handle_provider_auth_begin_login, "standard")),
        ("providerAuth.completeLogin", RpcRoute(handle_provider_auth_complete_login, "standard")),
        ("providerAuth.logout", RpcRoute(handle_provider_auth_logout, "standard")),
        ("messaging.config.get", RpcRoute(handle_messaging_config_get, "without_params")),
        ("messaging.config.update", RpcRoute(handle_messaging_config_update, "standard")),
        ("messaging.test", RpcRoute(handle_messaging_test, "standard")),
        ("messaging.destinations.list", RpcRoute(handle_messaging_destinations_list, "without_params")),
        ("messaging.destinations.upsert", RpcRoute(handle_messaging_destinations_upsert, "standard")),
        ("messaging.destinations.delete", RpcRoute(handle_messaging_destinations_delete, "standard")),
        ("messaging.routes.list", RpcRoute(handle_messaging_routes_list, "without_params")),
        ("messaging.routes.upsert", RpcRoute(handle_messaging_routes_upsert, "standard")),
        ("messaging.routes.delete", RpcRoute(handle_messaging_routes_delete, "standard")),
        ("messaging.routes.resolve", RpcRoute(handle_messaging_routes_resolve, "standard")),
        ("market.dashboard.get", RpcRoute(handle_market_dashboard_get, "standard")),
        ("market.ticker.get", RpcRoute(handle_market_ticker_get, "standard")),
        ("market.chart.series.get", RpcRoute(handle_market_chart_series_get, "standard")),
        ("market.chart.formulas.get", RpcRoute(handle_market_chart_formulas_get, "standard")),
        ("market.ticker.evidence.get", RpcRoute(handle_market_ticker_evidence_get, "standard")),
        ("market.ticker.fundamentals.get", RpcRoute(handle_market_ticker_fundamentals_get, "standard")),
        ("market.financial.series.get", RpcRoute(handle_market_financial_series_get, "standard")),
        ("market.financial.metrics.list", RpcRoute(handle_market_financial_metrics_list, "standard")),
        ("market.universe.get", RpcRoute(handle_market_universe_get, "standard")),
        ("market.refresh", RpcRoute(handle_market_refresh, "standard")),
        ("market.interpret", RpcRoute(handle_market_interpret, "standard")),
        ("market.read.get", RpcRoute(handle_market_read_get, "standard")),
        ("market.brief.get", RpcRoute(handle_market_brief_get, "standard")),
        ("market.brief.run", RpcRoute(handle_market_brief_run, "standard")),
        ("market.calendar.get", RpcRoute(handle_market_calendar_get, "standard")),
        ("market.yield_curve.get", RpcRoute(handle_market_yield_curve_get, "standard")),
        ("market.ledger.get", RpcRoute(handle_market_ledger_get, "standard")),
        ("market.webull.status", RpcRoute(handle_market_webull_status, "standard")),
        ("market.webull.auth", RpcRoute(handle_market_webull_auth, "standard")),
        ("market.webull.accounts", RpcRoute(handle_market_webull_accounts, "standard")),
        ("market.webull.account.select", RpcRoute(handle_market_webull_account_select, "standard")),
        ("market.webull.sync", RpcRoute(handle_market_webull_sync, "standard")),
        ("market.webull.orders.sync", RpcRoute(handle_market_webull_orders_sync, "standard")),
        ("market.webull.pnl.get", RpcRoute(handle_market_webull_pnl_get, "standard")),
        ("market.webull.watchlists.import", RpcRoute(handle_market_webull_watchlists_import, "standard")),
        ("market.backtest.run", RpcRoute(handle_market_backtest_run, "standard")),
        ("market.backtest.stress_test", RpcRoute(handle_market_backtest_stress_test, "standard")),
        ("market.watchlist.get", RpcRoute(handle_market_watchlist_get, "standard")),
        ("market.watchlist.add", RpcRoute(handle_market_watchlist_add, "standard")),
        ("market.watchlist.remove", RpcRoute(handle_market_watchlist_remove, "standard")),
        ("market.watchlist.list.create", RpcRoute(handle_market_watchlist_list_create, "standard")),
        ("market.watchlist.list.delete", RpcRoute(handle_market_watchlist_list_delete, "standard")),
        ("market.watchlist.list.select", RpcRoute(handle_market_watchlist_list_select, "standard")),
        ("market.watchlist.list.role", RpcRoute(handle_market_watchlist_list_role, "standard")),
        ("market.symbols.search", RpcRoute(handle_market_symbols_search, "standard")),
        ("sessions.create", RpcRoute(handle_sessions_create, "standard")),
        ("sessions.merge.create", RpcRoute(handle_sessions_merge_create, "standard")),
        ("sessions.merge.state", RpcRoute(handle_sessions_merge_state, "standard")),
        ("sessions.rename", RpcRoute(handle_sessions_rename, "standard")),
        ("sessions.archive", RpcRoute(handle_sessions_archive, "standard")),
        ("sessions.artifacts", RpcRoute(handle_sessions_artifacts, "standard")),
        ("sessions.revertEdit", RpcRoute(handle_sessions_revert_edit, "standard")),
        ("workspace.listFiles", RpcRoute(handle_workspace_list_files, "standard")),
        ("workspace.readFile", RpcRoute(handle_workspace_read_file, "standard")),
        ("workspace.writeFile", RpcRoute(handle_workspace_write_file, "standard")),
        ("chat.decideApproval", RpcRoute(handle_chat_decide_approval, "standard")),
        ("approvals.list", RpcRoute(handle_approvals_list, "standard")),
        ("sessions.debugCopy", RpcRoute(handle_sessions_debug_copy, "standard")),
        ("sessions.export", RpcRoute(handle_sessions_export, "standard")),
        ("sessions.runs", RpcRoute(handle_sessions_runs, "standard")),
        ("sessions.run", RpcRoute(handle_sessions_run, "standard")),
        ("sessions.state", RpcRoute(handle_sessions_state, "standard")),
        ("sessions.resolve", RpcRoute(handle_sessions_resolve, "standard")),
        ("pulse.list", RpcRoute(handle_pulse_list, "standard")),
        ("pulse.create_from_session", RpcRoute(handle_pulse_create_from_session, "standard")),
        ("pulse.save", RpcRoute(handle_pulse_save, "standard")),
        ("pulse.dismiss", RpcRoute(handle_pulse_dismiss, "standard")),
        ("nasa.apod", RpcRoute(handle_nasa_apod, "standard")),
        ("nasa.apod.list", RpcRoute(handle_nasa_apod_list, "standard")),
        ("permissions.allowlist.list", RpcRoute(handle_permissions_allowlist_list, "without_params")),
        ("permissions.allowlist.add", RpcRoute(handle_permissions_allowlist_add, "standard")),
        ("permissions.allowlist.remove", RpcRoute(handle_permissions_allowlist_remove, "standard")),
        ("market.chart.workspace.get", RpcRoute(handle_chart_workspace_get, "broadcast")),
        ("market.chart.workspace.update", RpcRoute(handle_chart_workspace_update, "broadcast")),
        ("market.chart.capture", RpcRoute(handle_chart_capture, "broadcast")),
        ("market.chart.read", RpcRoute(handle_chart_read, "broadcast")),
        ("market.chart.document.get", RpcRoute(handle_chart_document_get, "broadcast")),
        ("market.chart.apply", RpcRoute(handle_chart_apply, "broadcast")),
        ("market.chart.undo", RpcRoute(handle_chart_undo, "broadcast")),
        ("market.chart.rendered", RpcRoute(handle_chart_rendered, "broadcast")),
        ("market.forecast.request", RpcRoute(request_forecast, "broadcast")),
        ("market.forecast.get", RpcRoute(get_forecast, "standard")),
        ("market.forecast.list", RpcRoute(list_forecasts, "standard")),
        ("market.forecast.cancel", RpcRoute(cancel_forecast, "standard")),
        ("market.forecast.amend", RpcRoute(amend_forecast, "standard")),
        ("market.forecast.tracking.update", RpcRoute(update_tracking, "standard")),
        ("market.forecast.rendered", RpcRoute(rendered_forecast, "standard")),
        ("market.screeners.get", RpcRoute(handle_market_screeners_get, "standard")),
        ("market.screeners.preview", RpcRoute(handle_market_screeners_preview, "standard")),
        ("market.screeners.run", RpcRoute(handle_market_screeners_run, "standard")),
        ("market.screeners.run.get", RpcRoute(handle_market_screeners_run_get, "standard")),
        ("market.screeners.handoff", RpcRoute(handle_market_screeners_handoff, "standard")),
        ("market.screeners.setup.get", RpcRoute(handle_market_screeners_setup_get, "standard")),
        ("market.scans.get", RpcRoute(handle_market_scans_get, "standard")),
        ("market.scans.save", RpcRoute(handle_market_scans_save, "standard")),
        ("market.scans.archive", RpcRoute(handle_market_scans_archive, "standard")),
        ("market.scans.preview", RpcRoute(handle_market_scans_preview, "standard")),
        ("market.scans.run", RpcRoute(handle_market_scans_run, "standard")),
        ("market.scans.run.get", RpcRoute(handle_market_scans_run_get, "standard")),
        ("market.alerts.list", RpcRoute(handle_market_alerts_list, "standard")),
        ("market.alerts.create", RpcRoute(handle_market_alerts_create, "standard")),
        ("market.alerts.save", RpcRoute(handle_market_alerts_save, "standard")),
        ("market.alerts.cancel", RpcRoute(handle_market_alerts_cancel, "standard")),
        ("market.alerts.state", RpcRoute(handle_market_alerts_state, "standard")),
        ("market.alerts.catalogue", RpcRoute(handle_market_alerts_catalogue, "standard")),
        ("market.notifications.get", RpcRoute(handle_market_notifications_get, "standard")),
        ("market.notifications.test", RpcRoute(handle_market_notifications_test, "standard")),
        ("market.notifications.action", RpcRoute(handle_market_notifications_action, "standard")),
        ("market.quote.subscribe", RpcRoute(handle_market_quote, "quote")),
        ("market.quote.unsubscribe", RpcRoute(handle_market_quote, "quote")),
    ]
)

CHART_RPC_METHODS = frozenset(
    method
    for method in RPC_ROUTES
    if method.startswith("market.chart.")
    and method not in {"market.chart.series.get", "market.chart.formulas.get"}
)
