import type { Briefing, MarketRead, MacroItem, Panel } from './types';
import { MM, PanelCard, PreviewBadge, label, mono, toneColor } from './marketUi';

export function modelStamp(model: string, generatedAt: string): string {
  try {
    const when = new Date(generatedAt).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
    return `${model} · ${when}`;
  } catch {
    return model;
  }
}

export function ModelBadge({ model, generatedAt }: { model: string; generatedAt: string }) {
  return (
    <span
      title="Generated by the model from computed facts — interpretation, not computation"
      style={{
        borderRadius: 999,
        border: `1px solid rgba(90,143,199,.35)`,
        background: 'rgba(90,143,199,.1)',
        padding: '3px 9px',
        font: '600 9px Inter',
        letterSpacing: '.1em',
        textTransform: 'uppercase',
        color: '#8fb8e8',
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
      }}
    >
      ✦ {modelStamp(model, generatedAt)}
    </span>
  );
}

export function Sparkline({ data, tone }: { data: number[]; tone: 'up' | 'down' | 'flat' }) {
  const w = 58;
  const h = 20;
  const mn = Math.min(...data);
  const mx = Math.max(...data);
  const rg = mx - mn || 1;
  const pts = data.map((y, i) => [(i / (data.length - 1)) * w, h - 2 - ((y - mn) / rg) * (h - 4)]);
  const d = 'M' + pts.map((p) => `${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' L');
  const col = toneColor(tone);
  return (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} style={{ display: 'block' }}>
      <path d={d} fill="none" stroke={col} strokeWidth={1.4} strokeLinecap="round" strokeLinejoin="round" opacity={0.9} />
      <circle cx={pts[pts.length - 1][0]} cy={pts[pts.length - 1][1]} r={1.8} fill={col} />
    </svg>
  );
}

const REGIME_LABELS: Record<string, string> = { 'risk-off': 'Risk-off', chop: 'Chop', 'risk-on': 'Risk-on', 'event-risk': 'Event-risk' };

export function BriefingHero({
  panel,
  onOpen,
  onExplain,
  read,
}: {
  panel: Panel<Briefing>;
  onOpen: (s: string) => void;
  onExplain: () => void;
  read?: MarketRead | null;
}) {
  // When a model read exists, it takes over the narrative fields; computed VIX/breadth stay factual.
  const b: Briefing = read
    ? {
        ...panel.data,
        headline: read.headline,
        emphasis: read.emphasis,
        summary: read.summary,
        attention: read.attention.map((a) => ({ kind: a.kind, label: a.symbol, glyph: '✦', symbol: a.symbol })),
      }
    : panel.data;
  const attentionWhy = read ? new Map(read.attention.map((a) => [a.symbol, a.why])) : null;
  const activeRegime = read?.regime ?? 'risk-on';
  const [before, after] = b.emphasis && b.headline.includes(b.emphasis) ? b.headline.split(b.emphasis) : [b.headline, ''];
  return (
    <div
      style={{
        position: 'relative',
        overflow: 'hidden',
        border: `1px solid ${MM.border}`,
        borderRadius: 16,
        background: `radial-gradient(130% 150% at 90% -30%, rgba(251,148,35,.11), transparent 52%), ${MM.panel}`,
        padding: '26px 28px',
        display: 'flex',
        gap: 30,
        alignItems: 'stretch',
        flexWrap: 'wrap',
      }}
    >
      <div style={{ flex: 1, minWidth: 320 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 11, flexWrap: 'wrap' }}>
          <span style={{ ...label, fontSize: 9.5, letterSpacing: '.16em' }}>Daily Briefing</span>
          <span
            style={{
              borderRadius: 999,
              border: `1px solid rgba(251,148,35,.28)`,
              background: MM.accentSoft,
              padding: '3px 9px',
              font: '600 9px Inter',
              letterSpacing: '.13em',
              textTransform: 'uppercase',
              color: MM.accent,
            }}
          >
            {REGIME_LABELS[activeRegime] ?? activeRegime}
          </span>
          {read ? <ModelBadge model={read.model} generatedAt={read.generatedAt} /> : <PreviewBadge status={panel.status} />}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', marginBottom: 15 }}>
          <span style={{ font: '600 8.5px Inter', letterSpacing: '.14em', textTransform: 'uppercase', color: MM.dim }}>What changed</span>
          {b.changed.map((ch, i) => (
            <span key={i} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 11.5, color: MM.textSoft }}>
              <span style={{ width: 4, height: 4, borderRadius: '50%', background: toneColor(ch.tone) }} />
              {ch.text}
            </span>
          ))}
        </div>
        <div onClick={onExplain} title="See why this read" style={{ cursor: 'pointer', marginBottom: 16 }}>
          <h1 style={{ margin: '0 0 12px', fontFamily: "'Cormorant Garamond', serif", fontWeight: 600, fontSize: 38, lineHeight: 1.08, letterSpacing: '-.01em', color: MM.text, maxWidth: 760 }}>
            {before}
            {after && <span style={{ color: MM.accent }}>{b.emphasis}</span>}
            {after}
          </h1>
          <p style={{ margin: '0 0 8px', fontSize: 14, lineHeight: 1.6, color: MM.muted, maxWidth: 640 }}>{b.summary}</p>
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, font: '600 10px Inter', letterSpacing: '.06em', textTransform: 'uppercase', color: MM.accent }}>Why this read →</span>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 9 }}>
          {b.attention.map((a, i) => (
            <button
              key={i}
              onClick={() => onOpen(a.symbol)}
              title={attentionWhy?.get(a.symbol) || undefined}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 9,
                cursor: 'pointer',
                border: `1px solid rgba(254,252,244,.08)`,
                background: MM.panelInset,
                borderRadius: 11,
                padding: '8px 13px 8px 10px',
                textAlign: 'left',
              }}
            >
              <span style={{ width: 24, height: 24, borderRadius: 7, background: MM.accentSoft, color: MM.accent, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11 }}>{a.glyph}</span>
              <span style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                <span style={{ font: '600 9px Inter', letterSpacing: '.1em', textTransform: 'uppercase', color: MM.dim }}>{a.kind}</span>
                <span style={{ fontSize: 12.5, fontWeight: 500, color: MM.text }}>{a.label}</span>
              </span>
            </button>
          ))}
        </div>
      </div>
      <div
        title={read?.regimeReasoning || undefined}
        style={{ flex: '0 0 210px', borderLeft: `1px solid ${MM.border}`, paddingLeft: 26, display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 16, cursor: read?.regimeReasoning ? 'help' : 'default' }}
      >
        <span style={{ ...label, letterSpacing: '.14em' }}>Regime read</span>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {(['risk-off', 'chop', 'risk-on', 'event-risk'] as const).map((key) => ({
            name: REGIME_LABELS[key],
            active: key === activeRegime,
            note: key === activeRegime ? 'now' : '',
          })).map((r) => (
            <div key={r.name} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <span style={{ width: 8, height: 8, borderRadius: '50%', background: r.active ? MM.accent : 'rgba(254,252,244,.14)', flex: '0 0 8px' }} />
              <span style={{ flex: 1, fontSize: 12, color: r.active ? MM.text : MM.dim, fontWeight: r.active ? 600 : 400 }}>{r.name}</span>
              <span style={{ fontFamily: mono, fontSize: 10, color: MM.dim }}>{r.note}</span>
            </div>
          ))}
        </div>
        <div style={{ borderTop: `1px solid ${MM.border}`, paddingTop: 12, display: 'flex', gap: 18 }}>
          <div>
            <div style={{ fontFamily: mono, fontSize: 17, color: MM.text }}>{b.vix}</div>
            <div style={{ font: '600 8.5px Inter', letterSpacing: '.1em', textTransform: 'uppercase', color: MM.dim, marginTop: 2 }}>VIX</div>
          </div>
          <div>
            <div style={{ fontFamily: mono, fontSize: 17, color: MM.up }}>{b.breadthPct}%</div>
            <div style={{ font: '600 8.5px Inter', letterSpacing: '.1em', textTransform: 'uppercase', color: MM.dim, marginTop: 2 }}>Breadth</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function MacroBoard({ panel }: { panel: Panel<MacroItem[]> }) {
  return (
    <PanelCard title="Macro Board — what's the weather" status={panel.status} right={<span style={{ fontSize: 11, color: MM.dim, fontStyle: 'italic' }}>5-day · close</span>}>
      <div style={{ display: 'flex', flexWrap: 'wrap' }}>
        {panel.data.map((m, i) => (
          <div key={i} style={{ flex: 1, minWidth: 120, padding: '0 16px', borderRight: i < panel.data.length - 1 ? `1px solid rgba(254,252,244,.05)` : 'none', display: 'flex', flexDirection: 'column', gap: 7 }}>
            <span style={{ font: '600 9px Inter', letterSpacing: '.12em', textTransform: 'uppercase', color: MM.dim }}>{m.label}</span>
            <div style={{ fontFamily: mono, fontSize: 18, color: MM.text, letterSpacing: '-.02em' }}>{m.value}</div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}>
              <span style={{ fontFamily: mono, fontSize: 11, color: toneColor(m.tone) }}>{m.change}</span>
              <Sparkline data={m.spark} tone={m.tone} />
            </div>
          </div>
        ))}
      </div>
    </PanelCard>
  );
}
